---
- name: Install IBM MQ Server from local tarball
  hosts: mq_hosts
  become: true
  vars:
    mq_user: mqm
    mq_group: mqm
    mq_date: "{{ lookup('pipe', 'date +%Y-%m-%d') }}"
    mq_dir: "/home/mqm/IBM_MQ_{{ mq_date }}"
    mq_tarball: "/root/9.4.0.0-IBM-MQ-LinuxX64.tar.gz"
    mq_server_host: "logstash-srv-01"

  tasks:
    - name: Ensure group mqm exists
      group:
        name: "{{ mq_group }}"
        state: present

    - name: Ensure user mqm exists with primary group mqm and set password
      user:
        name: "{{ mq_user }}"
        group: "{{ mq_group }}"
        password: "$6$BZiAqV9wphmNhi5W$u5U055nrQ7XLdSpbgSNaUgzNMyasx2QiWttmaHDLJ1aDcEX53GSO46ZN0APtmp72xNGhDa.sAWJenTmD9ki/t/"
        shell: /bin/bash
        state: present

    - name: Create installation directory with date
      file:
        path: "{{ mq_dir }}"
        state: directory
        mode: '0755'

    - name: Extract MQ tarball from /root/ to installation directory
      ansible.builtin.unarchive:
        src: "{{ mq_tarball }}"
        dest: "{{ mq_dir }}"
        remote_src: yes

    - name: Accept MQ license
      ansible.builtin.shell: |
        cd {{ mq_dir }}/MQServer
        echo "1" | ./mqlicense.sh -text_only
      args:
        executable: /bin/bash

    - name: Check if MQ is already installed
      ansible.builtin.command: /opt/mqm/bin/dspmqver
      register: mq_installed
      ignore_errors: true
  
    - name: Install IBM MQ RPMs (if not installed)
      ansible.builtin.shell: |
        cd {{ mq_dir }}/MQServer
        rpm -Uvh MQSeries*.rpm
      args:
        executable: /bin/bash
      when: mq_installed.rc != 0

    - name: Set MQ installation environment
      ansible.builtin.command: /opt/mqm/bin/setmqinst -i -p /opt/mqm/

    - name: Validate IBM MQ installation
      ansible.builtin.command: /opt/mqm/bin/dspmqver
      register: mq_version

    - name: Show MQ version
      ansible.builtin.debug:
        var: mq_version.stdout

    - name: Remove existing mqwebuser.xml
      file:
        path: /var/mqm/web/installations/Installation1/servers/mqweb/mqwebuser.xml
        state: absent

    - name: Copy basic_registry.xml to mqweb directory
      copy:
        src: /opt/mqm/web/mq/samp/configuration/basic_registry.xml
        dest: /var/mqm/web/installations/Installation1/servers/mqweb/basic_registry.xml
        remote_src: yes
        mode: '0644'

    - name: Rename basic_registry.xml to mqwebuser.xml
      command: >
        mv /var/mqm/web/installations/Installation1/servers/mqweb/basic_registry.xml
           /var/mqm/web/installations/Installation1/servers/mqweb/mqwebuser.xml

    - name: Change httpHost variable in mqweb.xml
      replace:
        path: /opt/mqm/web/mq/etc/mqweb.xml
        regexp: '<variable name="httpHost" value=".*?"/>'
        replace: '<variable name="httpHost" value="{{ mq_server_host }}"/>'

    - name: Start IBM MQ Web server
      ansible.builtin.command: /opt/mqm/bin/strmqweb
      become: true
      become_user: mqm
