---
- name: Ensure "hello world!" exists in /root/semaphore.txt
  hosts: all
  become: true

  tasks:
    - name: Create/update the file with "hello world!"
      ansible.builtin.lineinfile:
        path: /root/semaphore.txt
        line: "hello world!"
        create: yes  # Creates the file if it doesn't exist
        mode: '0644'  # Sets file permissions (optional)
